apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  name: persistent-volume-pv-master
  labels:
    type: local
    app: db-master
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/db-master"
  claimRef:
    namespace: default
    name: pvc-db-master
