apiVersion: v1
kind: Service
metadata:
  name: db-master
spec:
  ports:
    - port: 5432
  selector:
    app: db-master
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-master
spec:
  selector:
    matchLabels:
      app: db-master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-master
    spec:
      containers:
        - image: postgres:17.6
          name: db-master
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: "public"
          ports:
            - containerPort: 5432
              name: db
              hostPort: 5433
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data-master
      volumes:
        - name: db-data-master
          persistentVolumeClaim:
            claimName: pvc-db-master
