apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  name: persistent-volume-pv
  labels:
    type: local
    app: db
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/db"